/**
 * Economics concept cards for the Study tab: the fallback when Claude hasn't written today's concept.
 */

export type EconCard = { term: string; what: string; example: string; exam: string };

export const ECON_CARDS: EconCard[] = [
  { term: "Opportunity cost", what: "The value of the next best alternative you give up when you choose something.", example: "Money spent on HS2 could not be spent on local rail or the NHS. Every budget line has a shadow.", exam: "Use it in evaluation: a policy can work and still be the wrong choice if the alternative was better." },
  { term: "The 2% inflation target", what: "The Bank of England's Monetary Policy Committee sets Bank Rate to keep CPI inflation at 2%. The Bank has been operationally independent since 1997.", example: "CPI peaked at 11.1% in October 2022 after the energy shock, and the MPC raised rates repeatedly in response.", exam: "Independence matters because it makes the target credible: politicians can't cut rates before an election." },
  { term: "Monetary transmission mechanism", what: "How a change in Bank Rate feeds through to spending: via borrowing costs, saving incentives, asset prices, the exchange rate and expectations.", example: "With more UK households on fixed-rate mortgages than in the past, rate rises now bite more slowly.", exam: "Always mention time lags: often quoted as up to two years for the full effect." },
  { term: "Quantitative easing", what: "The central bank creates reserves to buy bonds, pushing down long-term interest rates when Bank Rate is already near zero.", example: "UK QE began in March 2009 and the stock of purchases reached £895bn after the pandemic.", exam: "Evaluate: it supported demand but also lifted asset prices, which tends to benefit people who already own assets." },
  { term: "Fiscal credibility", what: "Markets lend cheaply to governments they trust to manage borrowing. Lose that trust and borrowing costs jump.", example: "After the September 2022 mini-budget announced unfunded tax cuts, gilt yields spiked and the Bank of England stepped in to stabilise the market.", exam: "Great example for 'constraints on fiscal policy' and for why the OBR (created 2010) exists." },
  { term: "Price elasticity of demand", what: "How responsive quantity demanded is to a change in price. Below 1 is inelastic, above 1 is elastic.", example: "Tobacco and peak rail fares are inelastic, so raising the price raises revenue more than it cuts use.", exam: "PED changes over time: demand is usually more elastic in the long run as people find substitutes." },
  { term: "Negative externalities", what: "Costs of a transaction that fall on third parties, so the market overproduces compared with the social optimum.", example: "The Soft Drinks Industry Levy (2018) was tiered by sugar content, and many producers reformulated before it even started.", exam: "Note the design lesson: the levy changed firms' behaviour, not only consumers'." },
  { term: "Minimum wage and monopsony", what: "In a competitive model a wage floor causes unemployment. If employers have wage-setting power (monopsony), a minimum wage can raise pay and employment.", example: "The UK introduced the National Minimum Wage in 1999. The Low Pay Commission's research has found little overall harm to employment.", exam: "Strong evaluation: the outcome depends on market structure and on how high the floor is relative to median pay." },
  { term: "Comparative advantage", what: "Countries gain from specialising in what they give up least to produce, even if one country is better at everything.", example: "The UK exports financial and business services and imports much of its manufactured goods.", exam: "Limits: assumes no transport costs, mobile factors and ignores strategic or security concerns." },
  { term: "The multiplier", what: "An injection of spending raises income by more than its own size because it is re-spent. Its size depends on the marginal propensity to consume and on leakages.", example: "An open economy like the UK has a smaller multiplier than a large closed one because a lot leaks into imports.", exam: "Multipliers tend to be larger in recessions, when there is spare capacity and interest rates are low." },
  { term: "Automatic stabilisers", what: "Tax and benefit flows that cushion the cycle without any new decision: tax receipts fall and benefit spending rises in a downturn.", example: "During the pandemic the deficit widened partly automatically, on top of deliberate schemes such as furlough.", exam: "Distinguish them clearly from discretionary fiscal policy." },
  { term: "The Phillips curve", what: "A short-run trade-off between unemployment and inflation. In the long run, expectations adjust and the curve is vertical at the natural rate.", example: "The 1970s combined high inflation and high unemployment, which broke faith in a stable trade-off.", exam: "Link to expectations: a credible central bank keeps expectations anchored, flattening the short-run curve." },
  { term: "Cost-push vs demand-pull", what: "Inflation can come from rising costs (shifting SRAS left) or from excess demand (AD right). The right response differs.", example: "The 2021–23 surge began largely with energy and supply-chain costs, then broadened into wages and services.", exam: "Raising rates does not produce more gas: evaluate whether monetary policy suits a supply shock." },
  { term: "The UK productivity puzzle", what: "Output per hour in the UK has grown far more slowly since 2008 than its earlier trend, and lags the US, France and Germany.", example: "Suggested causes include weak business investment, regional gaps, and slow diffusion of best practice among firms.", exam: "Productivity is the main long-run driver of real wages, so it belongs in any living-standards essay." },
  { term: "Supply-side policy", what: "Measures that raise the economy's productive capacity: education, infrastructure, competition, tax and welfare reform.", example: "Apprenticeship funding, planning reform and full expensing of investment are recent UK examples.", exam: "Evaluation: long time lags, uncertain results, and some market-based reforms widen inequality." },
  { term: "Exchange rates and the J-curve", what: "A depreciation makes exports cheaper and imports dearer, but the trade balance may worsen first because volumes take time to respond.", example: "Sterling fell sharply after the June 2016 referendum. Import prices and inflation rose while the export boost was modest.", exam: "Bring in the Marshall–Lerner condition: the sum of export and import elasticities must exceed one." },
  { term: "Current account deficit", what: "A country spending more abroad than it earns, funded by borrowing or selling assets to foreigners.", example: "The UK has run a persistent deficit for decades, relying on what a former Bank governor called 'the kindness of strangers'.", exam: "A deficit is not automatically bad: it matters what it finances and how easily it can be funded." },
  { term: "Deficit vs debt", what: "The deficit is the annual gap between spending and revenue. The debt is the accumulated stock of past borrowing.", example: "UK public debt rose to around the size of annual GDP after the financial crisis and the pandemic.", exam: "Cutting the deficit only slows the growth of debt. Mixing them up is a classic lost mark." },
  { term: "Crowding out", what: "Government borrowing may push up interest rates and displace private investment.", example: "In 2009–2020, with rates near zero and spare capacity, crowding out was arguably weak.", exam: "Context decides: it is stronger near full employment, weaker in a slump." },
  { term: "Moral hazard", what: "When someone is protected from the consequences of risk, they take more of it.", example: "Northern Rock in 2007 was the first run on a UK bank in about 150 years. Bailouts raised the 'too big to fail' problem.", exam: "Connect to regulation: higher capital requirements and ring-fencing try to reduce it." },
  { term: "Asymmetric information", what: "One side of a deal knows more than the other, which can shrink or destroy a market.", example: "Akerlof's 'market for lemons': if buyers can't tell good used cars from bad, good cars get withdrawn.", exam: "Solutions are often non-price: warranties, MOTs, reviews, regulation." },
  { term: "Public goods", what: "Non-rival and non-excludable, so the free-rider problem means markets underprovide them.", example: "Flood defences and street lighting. Few things are pure public goods, so check both properties.", exam: "Don't confuse with merit goods such as education, which are rival and excludable but underconsumed." },
  { term: "Tragedy of the commons", what: "A shared resource gets overused because each user takes the full benefit and bears only a share of the cost.", example: "Fish stocks managed by quotas, and carbon priced through emissions trading schemes.", exam: "Compare solutions: property rights, quotas, taxes, tradable permits." },
  { term: "Price discrimination", what: "Charging different prices to different groups for the same product, based on willingness to pay.", example: "Peak and off-peak rail tickets, student discounts, airline seats bought early versus late.", exam: "Conditions: market power, separable groups with different PED, and no resale." },
  { term: "Oligopoly and interdependence", what: "A few large firms each watching the others, which makes prices sticky and non-price competition common.", example: "UK supermarkets compete on loyalty cards and price-match promises. Aldi and Lidl disrupted the big four.", exam: "Use game theory: the incentive to cheat explains why collusion is unstable." },
  { term: "Contestable markets", what: "What disciplines firms is the threat of entry, not the number of firms. Low sunk costs make hit-and-run entry possible.", example: "Low-cost airlines entering routes pushed incumbent fares down.", exam: "Evaluate how contestable a market really is: brand loyalty and landing slots are sunk costs." },
  { term: "Natural monopoly", what: "Fixed costs so large that one firm can serve the market more cheaply than two.", example: "Water networks and the National Grid, regulated by Ofwat and Ofgem with price caps.", exam: "Regulatory capture and under-investment are the standard evaluation points, and water is a live example." },
  { term: "Nudges", what: "Changing how choices are presented to steer decisions without banning anything or changing prices much.", example: "Automatic pension enrolment from 2012 sharply raised workplace pension saving because most people stay with the default.", exam: "Cheap and popular, but effects can be small and raise questions about who decides what is good for you." },
  { term: "Inequality: Lorenz and Gini", what: "The Lorenz curve plots cumulative income share. The Gini coefficient runs from 0 (perfect equality) to 1.", example: "UK income inequality rose sharply in the 1980s and has been broadly flat since. Wealth is far more unequal than income.", exam: "Separate income from wealth, and before-tax from after-tax-and-benefits." },
  { term: "The Laffer curve", what: "Beyond some rate, higher taxes reduce revenue because they blunt incentives or encourage avoidance.", example: "The debate over the UK's 50p top rate (2010–13) turned on how much high earners shifted income.", exam: "The curve's existence is uncontroversial. Where the peak sits is the real argument." },
  { term: "Protectionism", what: "Tariffs, quotas and subsidies that shield domestic producers from imports.", example: "US steel tariffs and the US–China trade war raised costs for American manufacturers using steel.", exam: "Infant-industry and national-security arguments are the strongest, retaliation the biggest risk." },
  { term: "GDP and living standards", what: "GDP per head measures output, not wellbeing. It misses distribution, unpaid work, leisure and environmental damage.", example: "The UN's Human Development Index adds life expectancy and education to income.", exam: "Always adjust for inflation, population and purchasing power before comparing countries." },
  { term: "Housing supply", what: "Supply of housing is price inelastic, especially in the short run, so rising demand mainly raises prices.", example: "Planning constraints and slow build rates are widely blamed for UK affordability problems.", exam: "A demand-side fix like Help to Buy can push prices up further if supply can't respond." },
  { term: "Types of unemployment", what: "Cyclical (weak demand), structural (skills or location mismatch), frictional (between jobs) and seasonal.", example: "The decline of coal and steel left structural unemployment in parts of Wales and the North for decades.", exam: "Match the policy to the type: demand stimulus does little for structural unemployment." },
];

/** Stable index for a date key, so the fact of the day is the same on phone and laptop. */
export function indexForDate(dateKey: string, length: number, salt = 0): number {
  let h = salt;
  for (let i = 0; i < dateKey.length; i++) h = (h * 31 + dateKey.charCodeAt(i)) >>> 0;
  return h % length;
}
