/**
 * Content for the Daily tab. Written for this app, kept to claims with decent evidence behind them,
 * and deliberately free of food rules, calorie talk or supplement pushing.
 */

export type HealthFact = { title: string; body: string; tryIt: string };

export const HEALTH_FACTS: HealthFact[] = [
  { title: "Morning light sets your clock", body: "Light hitting your eyes soon after waking tells your brain what time it is, which shapes when you feel alert and when you get sleepy that night. Even a grey sky is many times brighter than indoor lighting.", tryIt: "Five to ten minutes outside before you look at a screen." },
  { title: "Caffeine hangs around", body: "Caffeine's half-life is roughly five hours, and longer for some people. Half of a 4pm coffee can still be in your system at 9pm, quietly making sleep lighter even if you fall asleep fine.", tryIt: "Keep caffeine to the morning." },
  { title: "Regular beats long", body: "Going to bed and getting up at about the same time is one of the strongest predictors of good sleep. A big weekend lie-in works like mini jet lag on Monday morning.", tryIt: "Keep weekend wake-ups within an hour of your weekday time." },
  { title: "A long exhale is a brake pedal", body: "Breathing out slower than you breathe in nudges the nervous system towards calm and drops heart rate within a minute or two. It works before a test, a free throw or bed.", tryIt: "In for 4, out for 8. Ten rounds." },
  { title: "Winter sun can't make vitamin D here", body: "From about October to March the sun sits too low over the UK for skin to make vitamin D. That is why the NHS suggests everyone considers a daily 10 microgram supplement over winter.", tryIt: "It is the one supplement that is plain public-health advice." },
  { title: "Sleep is when learning sticks", body: "Memories from the day are replayed and filed during deep and REM sleep. Studying late and cutting sleep short trades away exactly the process that makes revision last.", tryIt: "Finish the block, then protect the full night." },
  { title: "Testing yourself beats rereading", body: "Pulling an answer out of your head strengthens the memory far more than looking at it again. It feels harder, and that difficulty is the point.", tryIt: "Blank page, write everything you know, then check." },
  { title: "Bright evenings push sleep later", body: "Strong light late at night suppresses melatonin and tells your body it is still daytime. Overhead lights and close-up screens are the usual culprits.", tryIt: "Lamps instead of ceiling lights after dinner." },
  { title: "A short walk after eating helps", body: "Ten to fifteen minutes of easy walking after a meal smooths out the rise in blood sugar and tends to leave people feeling less sluggish afterwards.", tryIt: "Walk part of the way back after lunch." },
  { title: "Exercise is a study tool", body: "A bout of movement raises alertness and a growth factor called BDNF that supports learning. People concentrate better for a while after even a brisk walk.", tryIt: "Move first, then sit down to the hard topic." },
  { title: "Mild dehydration costs focus", body: "Losing only a percent or two of body weight in fluid is enough to dent attention and mood. After training or a night's sleep you usually start a little behind.", tryIt: "A glass of water on waking and after sport." },
  { title: "Habits take about two months", body: "In one well-known study, a new daily behaviour took around 66 days on average to feel automatic, with a wide range between people. Missing a single day made no measurable difference.", tryIt: "A miss is not a reset. Just do the next one." },
  { title: "If-then plans work", body: "People who decide in advance exactly when and where they'll act follow through far more often than people who only intend to. The plan does the remembering for you.", tryIt: "'When I get home, phone goes in the kitchen, then I start the block.'" },
  { title: "Friends are a health behaviour", body: "A large review of 148 studies found people with strong relationships were about 50% more likely to be alive at follow-up, an effect in the same league as quitting smoking.", tryIt: "One proper conversation today that isn't on a screen." },
  { title: "Two hours a week in nature", body: "A study of nearly 20,000 people in England found those who spent at least 120 minutes a week in green or blue space reported better health and wellbeing. How the time was split did not matter.", tryIt: "A long weekend walk covers most of it." },
  { title: "Warm-ups prevent injuries", body: "Structured warm-ups with balance, jumping and landing drills have cut injuries in youth team sports by around a third or more in trials. Knees and ankles benefit most.", tryIt: "Ten deliberate minutes before basketball, not two." },
  { title: "Stretch after, move before", body: "Long static holds right before explosive sport can slightly blunt power. Dynamic movement warms you up better, and static stretching fits well afterwards.", tryIt: "Leg swings and lunges pre-game, long holds at night." },
  { title: "Strength now is banked for later", body: "Bone density peaks in your twenties, and loading the skeleton with resistance training and jumping in your late teens helps build the peak you'll draw on for decades.", tryIt: "Two short, hard strength sessions a week is plenty." },
  { title: "Daylight protects eyesight", body: "Children and teenagers who spend more time outdoors are less likely to become short-sighted. Bright outdoor light seems to be the protective factor, not what you look at.", tryIt: "Lunch break outside counts." },
  { title: "Naps: short and early", body: "A 10 to 20 minute nap restores alertness without grogginess. Longer or later naps dip into deep sleep and can steal from the night.", tryIt: "Before 3pm, alarm set for 20 minutes." },
  { title: "Cool rooms sleep better", body: "Your core temperature needs to fall a little to fall asleep. A bedroom around 16 to 18°C, with warm bedding, generally beats a warm room.", tryIt: "Window open a crack, heating off in the bedroom." },
  { title: "Alcohol is not a sleep aid", body: "It can knock you out faster, but it fragments the second half of the night and suppresses REM sleep, so you wake less restored.", tryIt: "Worth knowing before it becomes a habit." },
  { title: "Nicotine hooks fast, especially young", body: "The brain keeps developing into the mid-twenties and is more prone to nicotine dependence before then. Vapes and pouches deliver it just as effectively as cigarettes.", tryIt: "Never starting is the whole strategy." },
  { title: "Breaking up sitting matters", body: "Standing up and moving for a couple of minutes every half hour improves blood sugar handling and energy compared with sitting straight through, even with the same total exercise.", tryIt: "Stand and stretch between past-paper questions." },
  { title: "Resting heart rate is a dashboard", body: "As aerobic fitness improves, resting heart rate drifts down. A sudden rise of several beats over your normal can flag poor sleep, illness coming on or too much training.", tryIt: "Notice the trend, not single days." },
  { title: "Nose breathing does real work", body: "The nose warms, humidifies and filters air and adds nitric oxide, which helps oxygen uptake. At rest and during easy exercise, nasal breathing is the default worth keeping.", tryIt: "Easy walks with your mouth closed." },
  { title: "Twenty-twenty-twenty", body: "Staring at near work for hours tires the focusing muscles of the eye. Looking at something far away for a few seconds at regular intervals relieves it.", tryIt: "Every 20 minutes, 20 seconds, something 20 feet away." },
  { title: "Protein early keeps you steadier", body: "Breakfasts with a decent amount of protein tend to keep people fuller and more even through the morning than ones that are mostly sugar.", tryIt: "Eggs, yoghurt or milk with whatever else you like." },
  { title: "Plants feed your gut bugs", body: "Fibre from a variety of plants is fermented by gut bacteria into short-chain fatty acids that help maintain the gut lining. Variety seems to matter as much as amount.", tryIt: "Add, don't subtract: one extra plant on the plate." },
  { title: "Writing down good things works, modestly", body: "Trials of gratitude journaling show small but real improvements in mood and sleep. The effect comes from doing it regularly, not from writing a lot.", tryIt: "One line in the journal tonight." },
  { title: "Phones cost attention just by being there", body: "In experiments, having your own phone in view during a demanding task slightly worsened performance, even when it never rang. Part of your attention stays on it.", tryIt: "Another room, not face down on the desk." },
  { title: "Cold water wakes you up", body: "A cold finish to a shower triggers a burst of noradrenaline and a jump in alertness. The evidence for bigger claims is thin, but as a morning wake-up it does what it says.", tryIt: "Thirty seconds, mornings only, skip it if you're ill." },
  { title: "Midday is the brightest you'll get", body: "In a British winter the hour around noon carries most of the day's usable daylight. Catching it supports both body clock and mood when mornings and evenings are dark.", tryIt: "Eat, then fifteen minutes outside." },
  { title: "Confidence follows evidence", body: "Self-belief tracks your own record of doing what you said you would. Small promises kept daily build it faster than big goals occasionally chased.", tryIt: "Tick the list. That is the evidence." },
];

export type EconCard = { term: string; what: string; example: string; exam: string };

export const ECON_CARDS: EconCard[] = [
  { term: "Opportunity cost", what: "The value of the next best alternative you give up when you choose something.", example: "Money spent on HS2 could not be spent on local rail or the NHS. Every budget line has a shadow.", exam: "Use it in evaluation: a policy can work and still be the wrong choice if the alternative was better." },
  { term: "The 2% inflation target", what: "The Bank of England's Monetary Policy Committee sets Bank Rate to keep CPI inflation at 2%. The Bank has been operationally independent since 1997.", example: "CPI peaked at 11.1% in October 2022 after the energy shock, and the MPC raised rates repeatedly in response.", exam: "Independence matters because it makes the target credible: politicians can't cut rates before an election." },
  { term: "Monetary transmission mechanism", what: "How a change in Bank Rate feeds through to spending: via borrowing costs, saving incentives, asset prices, the exchange rate and expectations.", example: "With more UK households on fixed-rate mortgages than in the past, rate rises now bite more slowly.", exam: "Always mention time lags: often quoted as up to two years for the full effect." },
  { term: "Quantitative easing", what: "The central bank creates reserves to buy bonds, pushing down long-term interest rates when Bank Rate is already near zero.", example: "UK QE began in March 2009 and the stock of purchases reached £895bn after the pandemic.", exam: "Evaluate: it supported demand but also lifted asset prices, which tends to benefit people who already own assets." },
  { term: "Fiscal credibility", what: "Markets lend cheaply to governments they trust to manage borrowing. Lose that trust and borrowing costs jump.", example: "After the September 2022 mini-budget announced unfunded tax cuts, gilt yields spiked and the Bank of England stepped in to stabilise the market.", exam: "Great example for 'constraints on fiscal policy' and for why the OBR (created 2010) exists." },
  { term: "Price elasticity of demand", what: "How responsive quantity demanded is to a change in price. Below 1 is inelastic, above 1 is elastic.", example: "Tobacco and peak rail fares are inelastic, so raising the price raises revenue more than it cuts use.", exam: "PED changes over time: demand is usually more elastic in the long run as people find substitutes." },
  { term: "Negative externalities", what: "Costs of a transaction that fall on third parties, so the market overproduces compared with the social optimum.", example: "The Soft Drinks Industry Levy (2018) was tiered by sugar content, and many producers reformulated before it even started.", exam: "Note the design lesson: the levy changed firms' behaviour, not only consumers'." },
  { term: "Minimum wage and monopsony", what: "In a competitive model a wage floor causes unemployment. If employers have wage-setting power (monopsony), a minimum wage can raise pay and employment.", example: "The UK introduced the National Minimum Wage in 1999. The Low Pay Commission's research has found little overall harm to employment.", exam: "Strong evaluation: the outcome depends on market structure and on how high the floor is relative to median pay." },
  { term: "Comparative advantage", what: "Countries gain from specialising in what they give up least to produce, even if one country is better at everything.", example: "The UK exports financial and business services and imports much of its manufactured goods.", exam: "Limits: assumes no transport costs, mobile factors and ignores strategic or security concerns." },
  { term: "The multiplier", what: "An injection of spending raises income by more than its own size because it is re-spent. Its size depends on the marginal propensity to consume and on leakages.", example: "An open economy like the UK has a smaller multiplier than a large closed one because a lot leaks into imports.", exam: "Multipliers tend to be larger in recessions, when there is spare capacity and interest rates are low." },
  { term: "Automatic stabilisers", what: "Tax and benefit flows that cushion the cycle without any new decision: tax receipts fall and benefit spending rises in a downturn.", example: "During the pandemic the deficit widened partly automatically, on top of deliberate schemes such as furlough.", exam: "Distinguish them clearly from discretionary fiscal policy." },
  { term: "The Phillips curve", what: "A short-run trade-off between unemployment and inflation. In the long run, expectations adjust and the curve is vertical at the natural rate.", example: "The 1970s combined high inflation and high unemployment, which broke faith in a stable trade-off.", exam: "Link to expectations: a credible central bank keeps expectations anchored, flattening the short-run curve." },
  { term: "Cost-push vs demand-pull", what: "Inflation can come from rising costs (shifting SRAS left) or from excess demand (AD right). The right response differs.", example: "The 2021–23 surge began largely with energy and supply-chain costs, then broadened into wages and services.", exam: "Raising rates does not produce more gas: evaluate whether monetary policy suits a supply shock." },
  { term: "The UK productivity puzzle", what: "Output per hour in the UK has grown far more slowly since 2008 than its earlier trend, and lags the US, France and Germany.", example: "Suggested causes include weak business investment, regional gaps, and slow diffusion of best practice among firms.", exam: "Productivity is the main long-run driver of real wages, so it belongs in any living-standards essay." },
  { term: "Supply-side policy", what: "Measures that raise the economy's productive capacity: education, infrastructure, competition, tax and welfare reform.", example: "Apprenticeship funding, planning reform and full expensing of investment are recent UK examples.", exam: "Evaluation: long time lags, uncertain results, and some market-based reforms widen inequality." },
  { term: "Exchange rates and the J-curve", what: "A depreciation makes exports cheaper and imports dearer, but the trade balance may worsen first because volumes take time to respond.", example: "Sterling fell sharply after the June 2016 referendum. Import prices and inflation rose while the export boost was modest.", exam: "Bring in the Marshall–Lerner condition: the sum of export and import elasticities must exceed one." },
  { term: "Current account deficit", what: "A country spending more abroad than it earns, funded by borrowing or selling assets to foreigners.", example: "The UK has run a persistent deficit for decades, relying on what a former Bank governor called 'the kindness of strangers'.", exam: "A deficit is not automatically bad: it matters what it finances and how easily it can be funded." },
  { term: "Deficit vs debt", what: "The deficit is the annual gap between spending and revenue. The debt is the accumulated stock of past borrowing.", example: "UK public debt rose to around the size of annual GDP after the financial crisis and the pandemic.", exam: "Cutting the deficit only slows the growth of debt. Mixing them up is a classic lost mark." },
  { term: "Crowding out", what: "Government borrowing may push up interest rates and displace private investment.", example: "In 2009–2020, with rates near zero and spare capacity, crowding out was arguably weak.", exam: "Context decides: it is stronger near full employment, weaker in a slump." },
  { term: "Moral hazard", what: "When someone is protected from the consequences of risk, they take more of it.", example: "Northern Rock in 2007 was the first run on a UK bank in about 150 years. Bailouts raised the 'too big to fail' problem.", exam: "Connect to regulation: higher capital requirements and ring-fencing try to reduce it." },
  { term: "Asymmetric information", what: "One side of a deal knows more than the other, which can shrink or destroy a market.", example: "Akerlof's 'market for lemons': if buyers can't tell good used cars from bad, good cars get withdrawn.", exam: "Solutions are often non-price: warranties, MOTs, reviews, regulation." },
  { term: "Public goods", what: "Non-rival and non-excludable, so the free-rider problem means markets underprovide them.", example: "Flood defences and street lighting. Few things are pure public goods, so check both properties.", exam: "Don't confuse with merit goods such as education, which are rival and excludable but underconsumed." },
  { term: "Tragedy of the commons", what: "A shared resource gets overused because each user takes the full benefit and bears only a share of the cost.", example: "Fish stocks managed by quotas, and carbon priced through emissions trading schemes.", exam: "Compare solutions: property rights, quotas, taxes, tradable permits." },
  { term: "Price discrimination", what: "Charging different prices to different groups for the same product, based on willingness to pay.", example: "Peak and off-peak rail tickets, student discounts, airline seats bought early versus late.", exam: "Conditions: market power, separable groups with different PED, and no resale." },
  { term: "Oligopoly and interdependence", what: "A few large firms each watching the others, which makes prices sticky and non-price competition common.", example: "UK supermarkets compete on loyalty cards and price-match promises. Aldi and Lidl disrupted the big four.", exam: "Use game theory: the incentive to cheat explains why collusion is unstable." },
  { term: "Contestable markets", what: "What disciplines firms is the threat of entry, not the number of firms. Low sunk costs make hit-and-run entry possible.", example: "Low-cost airlines entering routes pushed incumbent fares down.", exam: "Evaluate how contestable a market really is: brand loyalty and landing slots are sunk costs." },
  { term: "Natural monopoly", what: "Fixed costs so large that one firm can serve the market more cheaply than two.", example: "Water networks and the National Grid, regulated by Ofwat and Ofgem with price caps.", exam: "Regulatory capture and under-investment are the standard evaluation points, and water is a live example." },
  { term: "Nudges", what: "Changing how choices are presented to steer decisions without banning anything or changing prices much.", example: "Automatic pension enrolment from 2012 sharply raised workplace pension saving because most people stay with the default.", exam: "Cheap and popular, but effects can be small and raise questions about who decides what is good for you." },
  { term: "Inequality: Lorenz and Gini", what: "The Lorenz curve plots cumulative income share. The Gini coefficient runs from 0 (perfect equality) to 1.", example: "UK income inequality rose sharply in the 1980s and has been broadly flat since. Wealth is far more unequal than income.", exam: "Separate income from wealth, and before-tax from after-tax-and-benefits." },
  { term: "The Laffer curve", what: "Beyond some rate, higher taxes reduce revenue because they blunt incentives or encourage avoidance.", example: "The debate over the UK's 50p top rate (2010–13) turned on how much high earners shifted income.", exam: "The curve's existence is uncontroversial. Where the peak sits is the real argument." },
  { term: "Protectionism", what: "Tariffs, quotas and subsidies that shield domestic producers from imports.", example: "US steel tariffs and the US–China trade war raised costs for American manufacturers using steel.", exam: "Infant-industry and national-security arguments are the strongest, retaliation the biggest risk." },
  { term: "GDP and living standards", what: "GDP per head measures output, not wellbeing. It misses distribution, unpaid work, leisure and environmental damage.", example: "The UN's Human Development Index adds life expectancy and education to income.", exam: "Always adjust for inflation, population and purchasing power before comparing countries." },
  { term: "Housing supply", what: "Supply of housing is price inelastic, especially in the short run, so rising demand mainly raises prices.", example: "Planning constraints and slow build rates are widely blamed for UK affordability problems.", exam: "A demand-side fix like Help to Buy can push prices up further if supply can't respond." },
  { term: "Types of unemployment", what: "Cyclical (weak demand), structural (skills or location mismatch), frictional (between jobs) and seasonal.", example: "The decline of coal and steel left structural unemployment in parts of Wales and the North for decades.", exam: "Match the policy to the type: demand stimulus does little for structural unemployment." },
];

/** Stable index for a date key, so the fact of the day is the same on phone and laptop. */
export function indexForDate(dateKey: string, length: number, salt = 0): number {
  let h = salt;
  for (let i = 0; i < dateKey.length; i++) h = (h * 31 + dateKey.charCodeAt(i)) >>> 0;
  return h % length;
}
